apiVersion: v2
appVersion: 0.54.0
description: Web-based MongoDB admin interface, written with Node.js and express
home: https://github.com/mongo-express/mongo-express
icon: https://raw.githubusercontent.com/mongo-express/mongo-express/master/public/images/mongo-express-logo.png
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: mongo-express
version: 3.0.0
dependencies:
  - name: common
    version: 1.7.1
    repository: https://charts.bitnami.com/bitnami/
  - name: mongodb
    version: 12.1.20
    repository: https://charts.bitnami.com/bitnami/
    condition: mongodb.enabled
