apiVersion: v2
appVersion: 0.8.1
description: Enables running a server to display Lighthouse CI results
home: https://github.com/GoogleChrome/lighthouse-ci
icon: https://raw.githubusercontent.com/GoogleChrome/lighthouse-ci/master/packages/server/src/ui/logo.svg
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: lighthouse-ci
sources:
  - https://github.com/GoogleChrome/lighthouse-ci
version: 3.0.0
dependencies:
  - name: common
    version: 1.7.1
    repository: https://charts.bitnami.com/bitnami/
  - name: mariadb
    version: 11.0.13
    repository: https://charts.bitnami.com/bitnami/
    condition: mariadb.enabled
  - name: postgresql
    version: 11.6.8
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
